try {
    let a = 0
    log = log
    console.log("Program Run Successfully");
} catch (error) {
    log = log
    console.log("This is an Error");
}

finally {
    console.log("This is run due to finally");
}
// console.log("This is a good boy");